-- Creating a table to manage Angi Technicians BGV Status
CREATE TABLE angi_bgv_tracker (
    tech_id INT PRIMARY KEY,
    name VARCHAR(100),
    entry_type VARCHAR(50), -- New Entry or Re-verification
    criminal_record_found BOOLEAN DEFAULT FALSE,
    ai_risk_score INT, -- Score generated by Gen AI
    final_status VARCHAR(20) -- Approved, Rejected, Pending
);

-- Query to find all technicians who need Gen AI verification
SELECT * FROM angi_bgv_tracker 
WHERE final_status = 'Pending' AND entry_type = 'New Entry';

-- Query to update status after AI analysis
UPDATE angi_bgv_tracker 
SET final_status = 'Approved', ai_risk_score = 10 
WHERE tech_id = 101;